

export const CHANGE_TITLE = "HELLOWORLD/CHANGE_TITLE";

export const GET_INFOR = "HELLOWORLD/GET_INFOR";

export const GET_INFOR_SUCCESS = "HELLOWORLD/GET_INFOR_SUCCESS";

export const GET_INFOR_FAILED = "HELLOWORLD/GET_INFOR_FAILED";